spring.application.name=CurrencyXchange

# API Key
api.exchangerate.key=d0fa5745f06622b99098b558

# Webflux optim
spring.webflux.base-path=/api
server.port=8080

logging.level.org.springframework.web=DEBUG
logging.level.reactor.netty=DEBUG
